# Generated by Django 5.0.7 on 2024-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_funeral_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeral',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
